openapi: 3.0.0
info:
  title: SecureTheTask API
  description: API for SecureTheTask, a full-stack task management application.
  version: 1.0.0

servers:
  - url: https://securetasklist.local:3000/api
    description: Secure development server

paths:
  /tasks:
    get:
      summary: Retrieve a list of tasks
      parameters:
        - name: search
          in: query
          schema:
            type: string
          description: Search query
        - name: status
          in: query
          schema:
            type: string
            enum:
              - "_0"
              - "_1"
              - "_2"
              - "_3"
          description: Filter by status
        - name: priority
          in: query
          schema:
            type: string
            enum:
              - "_0"
              - "_1"
              - "_2"
          description: Filter by priority
        - name: page
          in: query
          schema:
            type: integer
          description: Page number for pagination
        - name: limit
          in: query
          schema:
            type: integer
          description: Number of items per page
      responses:
        "200":
          description: A list of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Task"
    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "201":
          description: Task created

  /tasks/{taskId}:
    parameters:
      - name: taskId
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Retrieve a task by its ID
      responses:
        "200":
          description: Details of a task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
    put:
      summary: Update an existing task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "200":
          description: Task updated
    delete:
      summary: Delete a task
      responses:
        "204":
          description: Task deleted

  /authenticate:
    post:
      summary: Authenticate a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserCredentials"
      responses:
        "200":
          description: Authentication successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - title
        - status
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
        title:
          type: string
        description:
          type: string
        status:
          type: string
        priority:
          type: string
        dueDate:
          type: string
          format: date-time
    UserCredentials:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
